<?php

namespace Wlb\Crowdsourcing\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Psr\Http\Server\MiddlewareInterface;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use Wlb\Crowdsourcing\Services\StatisticService;

class LogPageHitMiddleware implements MiddlewareInterface
{
    public function __construct(
        private readonly StatisticService $statisticService
    ) {
    }

    /**
     * Processes the incoming server request and delegates to the given request handler.
     *
     * @param ServerRequestInterface $request The server request to be processed.
     * @param RequestHandlerInterface $handler The handler responsible for handling the request.
     * @return ResponseInterface The response generated by the request handler.
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $site = $request->getAttribute('site');
        if ($site !== null) {

            if (!isset($GLOBALS['TSFE']->tmpl->setup) || empty($GLOBALS['TSFE']->tmpl->setup)) {
                return $handler->handle($request);
            }

           $this->statisticService->log($request);
        }

        return $handler->handle($request);
    }
}