services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Wlb\Crowdsourcing\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Wlb\Crowdsourcing\Command\Import:
    tags:
      -
        name: console.command
        command: 'crowdsourcing:import'
        description: 'A command to import processes with their data.'
        schedulable: true
  Wlb\Crowdsourcing\Command\CleanupStaleProcessesCommand:
    tags:
      - name: 'console.command'
        command: 'crowdsourcing:stale-processes'

  Wlb\Crowdsourcing\Domain\Model\FrontendUser:
    public: true
    tags:
      -
        name: 'extender.extends'
        class: Evoweb\SfRegister\Domain\Model\FrontendUser
